---

- name: Install diamond system requirements
  apt: pkg={{ item }} update-cache=yes
  with_items:
    - python-pip
    - python-dev

- name: Install Diamond
  pip: name=diamond
       version={{ diamond_version|default(omit) }}

- name: Install diamond collector system requirements
  apt: pkg={{ item }}
  with_items: '{{ diamond_collector_system_requirements }}'

- name: Install diamond collector python requirements
  pip: name={{ item }}
  with_items: '{{ diamond_collector_python_requirements }}'

- name: Create Collectors Configuration path
  file: path={{ diamond_conf_path }}
        state=directory
